global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Node Exporter (시스템 리소스)
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Redis Exporter (추가 설치 필요)
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  # MySQL Exporter (추가 설치 필요)
  - job_name: "mysql"
    static_configs:
      - targets: ["mysqld-exporter:9104"]
